- name: Copy a file between remote hosts
  gather_facts: no
  hosts: Production
  tasks:
    - name: Copy the file from SFTP to Production server using Method Push
      synchronize:
        src: sftp_file.txt
        dest: sftp_file.txt
        mode: push
      delegate_to: SFTP
