- name: Copy a file between remote hosts
  gather_facts: no
  hosts: Production
  tasks:
  
    - name: Get info
      shell: export
      register: whoami
  
    - debug:
        msg: "{{ whoami }}"
      
        
