- name: Copy a file between remote hosts
  hosts: Production
  gather_facts: no
  tasks:
  
    - name: Fetch files
      shell: hostname
      vars:
        ansible_become: yes
        ansible_become_method: sudo
        ansible_host: SFTP
        ansible_become_user: "{{ sftp_user }}"
        ansible_become_passwword: "{{ sftp_pass }}"
       register: host_name
       delegate_to: localhost
      
    - debug: msg="{{ host_name }}"
      
        
