- name: Copy a file between remote hosts
  hosts: all
  gather_facts: no
  tasks:
  
  - name: Fetch file from server
    ansible.builtin.fetch:
      src: /tmp/sftp_file.txt
      dest: /tmp/sftp_file.txt
    delegate_to: localhost
