---
- hosts: all
  gather_facts: no
  tasks:

  - name: Copy file using sync module
    ansible.posix.synchronize:
      src: /tmp/sftp_file.txt
      dest: /tmp/sftp_file_definitive.txt
    delegate_to: localhost
